namespace RDPGW.Protocol;

internal enum HTTP_PACKET_TYPE : ushort
{
    PKT_TYPE_HANDSHAKE_REQUEST = 0x1,
    PKT_TYPE_HANDSHAKE_RESPONSE = 0x2,
    PKT_TYPE_EXTENDED_AUTH_MSG = 0x3,
    PKT_TYPE_TUNNEL_CREATE = 0x4,
    PKT_TYPE_TUNNEL_RESPONSE = 0x5,
    PKT_TYPE_TUNNEL_AUTH = 0x6,
    PKT_TYPE_TUNNEL_AUTH_RESPONSE = 0x7,
    PKT_TYPE_CHANNEL_CREATE = 0x8,
    PKT_TYPE_CHANNEL_RESPONSE = 0x9,
    PKT_TYPE_DATA = 0xA,
    PKT_TYPE_SERVICE_MESSAGE = 0xB,
    PKT_TYPE_REAUTH_MESSAGE = 0xC,
    PKT_TYPE_KEEPALIVE = 0xD,
    PKT_TYPE_CLOSE_CHANNEL = 0x10,
    PKT_TYPE_CLOSE_CHANNEL_RESPONSE = 0x11
}
