namespace RDPGW.Protocol;

internal enum HTTP_TUNNEL_RESPONSE_FIELDS_PRESENT_FLAGS : ushort
{
    HTTP_TUNNEL_RESPONSE_FIELD_TUNNEL_ID = 0x01,
    HTTP_TUNNEL_RESPONSE_FIELD_CAPS = 0x02,
    HTTP_TUNNEL_RESPONSE_FIELD_SOH_REQ = 0x04,
    HTTP_TUNNEL_RESPONSE_FIELD_CONSENT_MSG = 0x10,
}
