namespace RDPGW.Protocol;

internal enum HTTP_CAPABILITY_TYPE : uint
{
    HTTP_CAPABILITY_TYPE_QUAR_SOH = 0x1,
    HTTP_CAPABILITY_IDLE_TIMEOUT = 0x2,
    HTTP_CAPABILITY_MESSAGING_CONSENT_SIGN = 0x4,
    HTTP_CAPABILITY_MESSAGING_SERVICE_MSG = 0x8,
    HTTP_CAPABILITY_REAUTH = 0x10,
    HTTP_CAPABILITY_UDP_TRANSPORT = 0x20
}