namespace RDPGW.Protocol;

internal enum HTTP_TUNNEL_AUTH_RESPONSE_FIELDS_PRESENT_FLAGS : ushort
{
    HTTP_TUNNEL_AUTH_RESPONSE_FIELD_REDIR_FLAGS = 0x01,
    HTTP_TUNNEL_AUTH_RESPONSE_FIELD_IDLE_TIMEOUT = 0x02,
    HTTP_TUNNEL_AUTH_RESPONSE_FIELD_SOH_RESPONSE = 0x04,
}
