namespace RDPGW.Protocol;

internal enum HTTP_TUNNEL_REDIR_FLAGS : uint
{
    HTTP_TUNNEL_REDIR_ENABLE_ALL = 0x80000000,
    HTTP_TUNNEL_REDIR_DISABLE_ALL = 0x40000000,
    HTTP_TUNNEL_REDIR_DISABLE_DRIVE = 0x01,
    HTTP_TUNNEL_REDIR_DISABLE_PRINTER = 0x02,
    HTTP_TUNNEL_REDIR_DISABLE_PORT = 0x04,
    HTTP_TUNNEL_REDIR_DISABLE_CLIPBOARD = 0x08,
    HTTP_TUNNEL_REDIR_DISABLE_PNP = 0x10,
}
