namespace RDPGW.Protocol;

internal enum HTTP_CHANNEL_RESPONSE_FIELDS_PRESENT_FLAGS : ushort
{
    HTTP_CHANNEL_RESPONSE_FIELD_CHANNELID = 0x01,
    HTTP_CHANNEL_RESPONSE_FIELD_AUTHNCOOKIE = 0x02,
    HTTP_CHANNEL_RESPONSE_FIELD_UDPPORT = 0x04,
}
