# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish
    - name: Pack
      run:  dotnet pack --version-suffix "$(date +%s)"
    - name: Push
      env:
        NUGETAPIKEY: ${{ secrets.NUGETAPIKEY }}
      run: find RDPGW/bin/Release -type f -name '*.nupkg' -exec dotnet nuget push RDPGW/bin/Release/RDPGW.1.0.0.nupkg -k "$env:NUGETAPIKEY" \;
